<form action="/userstatus/index/save" method="POST" id="userstatus">
    <p>
    <ul>
        <li>
            <select id="customer_status" name="customer_status">
                <option value="1" <?= ($this->getUserStatusAttributeValue() == 1) ? 'selected' : ''; ?>>Active</option>
                <option value="0" <?= ($this->getUserStatusAttributeValue() == 0) ? 'selected' : ''; ?>>InActive
                </option>
            </select>
        </li>
    </ul>
    </p>
    <button type="submit" title="<?php echo $this->escapeHtml(__('Save')); ?>" class="button">
        <span><span><?php echo $this->escapeHtml(__('Save')); ?></span></span>
    </button>
</form>
